### ISSUE TITLE
Favicon 

### ISSUE THREAD

**Issue by AaronB432** [CSAllenISD/2023-ISP-ModelScheduler#104]
Change the favicon of every page of the website to be the same logo as the one that appears on the navbar.

**Comment by ryanhallock** [comment]
Please create PR to solve this issue if it is not already resolved, @AaronB432

**Comment by IsaacDaKing** [comment]
It should be resolved now, unless I'm misinterpreting something.

**Comment by GetJumpedOn95** [comment]
Yep it's resolved
