### ISSUE TITLE
Fix Course Selection Page

### ISSUE THREAD

**Issue by KrabbiePatty** [CSAllenISD/2023-ISP-ModelScheduler#106]
On the Courses page, whenever you try to remove classes they aren't removed from the selected courses but are added to available courses. Leading to a potentially infinite number of classes.

![Image](https://user-images.githubusercontent.com/89479023/218542847-fd07175b-fce4-44ac-9547-6fe4a1fc984b.PNG)

**Comment by Muq2** [comment]
Also limit the maximum classes selected to 8 maybe.

**Comment by LayneY** [comment]
This has been fixed. As long as classes have different sections then this should no longer happen.

**Comment by GetJumpedOn95** [comment]
Tested this out and seems to work.
