### ISSUE TITLE
Apply Dark mode to all pages

### ISSUE THREAD

**Issue by mdraeed** [CSAllenISD/2023-ISP-ModelScheduler#110]
Use existing dark mode code from index.js, index.html, and app.css to apply a dark mode to all pages.

**Comment by GetJumpedOn95** [comment]
Added the darkMode option to classes and FAQ pages. Dark mode can be toggled off and on for those pages just like the scheduler page.

**Comment by GetJumpedOn95** [comment]
Tested and verified Dark Mode worked on classes, scheduler and FAQ pages.
