### ISSUE TITLE
Set up Dark Mode for index.html

### ISSUE THREAD

**Issue by mdraeed** [CSAllenISD/2023-ISP-ModelScheduler#111]
Set up a dark mode in index.html that changes the background to a darker color.

**Comment by ryanhallock** [comment]
Please create a PR to resolve this issue, @mdraeed.

**Comment by mdraeed** [comment]
This was already completed, I must have forgotten to resolve the issue.

**Comment by GetJumpedOn95** [comment]
Verified dark mode was defined in index.html.
