### ISSUE TITLE
What does front end need from backend

### ISSUE THREAD

**Issue by Muq2** [CSAllenISD/2023-ISP-ModelScheduler#113]
List what frontend needs backend to get done below.

**Comment by ryanhallock** [comment]
The front end currently stores classes/selected schedules with JSON inside the browser's local storage, which is fine for an MVP. We could create a separate branch to include the login process and integrate it when the MVP is completed.

For routes, it seems we already have all the routes required, we only need to abstract them to an API endpoint like `GET: api/v1/courses` and return the classes.

**Comment by Muq2** [comment]
ok i’ll work on that on my local branch

**Comment by Muq2** [comment]
login process cannot be pushed yet, mail api is not ready and i do not want to display api keys.

**Comment by ryanhallock** [comment]
A .env file should be created on your local machine and a template .env file should be pushed without any secret keys. We also should put our hashing salt inside our .env file with other secret varaibles.

**Comment by GetJumpedOn95** [comment]
Ok I see
