### ISSUE TITLE
Search Bar Doesn't Work

### ISSUE THREAD

**Issue by KrabbiePatty** [CSAllenISD/2023-ISP-ModelScheduler#114]
On Courses, the search bar does not work. We need to fix it.

**Comment by IsaacDaKing** [comment]
Yes, this should definitely be a priority for the MVP. Otherwise this will be far to tedious to use.

**Comment by GetJumpedOn95** [comment]
I thought this was fixed?

**Comment by GetJumpedOn95** [comment]
i agree with Isaac we needed to get this done to make it more user friendly. Nice job
