### ISSUE TITLE
Consolidate CSS Pages

### ISSUE THREAD

**Issue by KrabbiePatty** [CSAllenISD/2023-ISP-ModelScheduler#115]
We need to merge most if not all of our CSS pages so that we have a homogenous styling throughout the website. Right now each page looks different.

**Comment by GetJumpedOn95** [comment]
It looks like most of the .html import their own .css and the app.css.  The app.css has some global settings defined.

**Comment by GetJumpedOn95** [comment]
I think this is an important feature to implement. It was hard trouble shooting different style issues and we had alot of repetitive code that is hard to maintain.
