### ISSUE TITLE
Courses page issues

### ISSUE THREAD

**Issue by June3333** [CSAllenISD/2023-ISP-ModelScheduler#118]
- [x] the Search bar doesnt work

- [ ] Whenever the user removes a course that have been added, it should go back to "available courses" in alphabetical order, not added to the bottom of the list

- [x]  Removal of some courses (physics calculus) doesnt work, resulting in duplication of classes in "available courses"

**Comment by IsaacDaKing** [comment]
>" Whenever the user removes a course that have been added, it should go back to "available courses" in alphabetical order, not added to the bottom of the list"

may be tedious to add, and may prove pointless given that we are going to add the search function, definitely the kind of issue we should have on the back-burner for now. It may more-or-less end up being resolved during the final gloss of the project
