### ISSUE TITLE
Naming Convention of webpages

### ISSUE THREAD

**Issue by IsaacDaKing** [CSAllenISD/2023-ISP-ModelScheduler#120]
In the title of each webpage (not the name of the file), what should we do? Should we just keep them all as a simply "Model Scheduler" or should we have it change in each webpage to reflect what that webpage is specifically for? If so, what method of organization and style do we intend to employ? Something like "Model Scheduler- Classes" or "Classes" or "AHS Classes" pr "Model Scheduler: Classes" etc etc you get the point

**Comment by ryanhallock** [comment]
I think we should expand on this idea and use names for files too like `FAQ.html` should be `faq.html` or `scheduler.html` could be `Scheduler.html`

**Comment by Muq2** [comment]
File names don’t matter?

**Comment by ryanhallock** [comment]
They do not, but it's more a preference thing. As we have camelcase with swift files but they are not required to be in that case.

**Comment by Muq2** [comment]
in my opinion html file names are fine as is

**Comment by ryanhallock** [comment]
It would be a good idea to create a more unified layout, common naming schemes with common page titles and a templated navbar.

**Comment by IsaacDaKing** [comment]
Yeah, the file names don't bother me too much, it may be tedious to change because we would also have to change all the links to it in the other webpages, and it may be more work than it's worth at this stage. That being said, we can still do it.

**Comment by GetJumpedOn95** [comment]
I agree with @ryanhallock, it is easier to navigate with meaningful names and common naming schemes.

**Comment by Muq2** [comment]
It is too late to change file names, it will cause lots of issues and require more work to rename everything everywhere. People who are editing those files locally will also have issues when pushing if you change them. Just leave the names how they are and work on actual functionality of the website 😁.

**Comment by IsaacDaKing** [comment]
Cute passive aggressiveness, but I agree, this is more for the titling of the web-page, not the file, something that is far less time-consuming to change.

**Comment by IsaacDaKing** [comment]
I think this is basically fixed, so I will close this for now. We'll say anyone can change the titles if they want, it probably doesn't matter, just make sure it's consistent.
