### ISSUE TITLE
scheduler page bug

### ISSUE THREAD

**Issue by June3333** [CSAllenISD/2023-ISP-ModelScheduler#126]
- [x] When a class is dragged and dropped to its original position, it creates an extra class on the classes list while not removing the original one
- [x]  When a whole year class is moved, it doesnt remove the class on the spring semester side 
- [ ] When a whole year class is moved from fall semester side to the same period spring semster side, the course disappears
- [ ] One privilege period fills out both semesters when there are 2 separate classes for each semester.
- [ ] one semester class disappears when a whole year class is scheduled in the same period in different semester

**Comment by IsaacDaKing** [comment]
"One privilege period fills out both semesters when there are 2 separate classes for each semester."
Doesn't that mean there's something wrong on Mr. Ben's side, or am I getting confused? I think he has control on whether the class is 2 semesters or 1. (please feel free to correct me)

**Comment by lumen-novum** [comment]
I'm pretty sure it's still considered to be one class because each class has an A and a B version for each semester that's automatically filled every time someone adds their class to the arena scheduler. I'm gonna close this issue.
