### ISSUE TITLE
Allow email validation to accept teacher and conselor email addresses

### ISSUE THREAD

**Issue by CSAllenISD** [CSAllenISD/2023-ISP-ModelScheduler#127]
Both counselors and teachers may also use the app.  Allow any address that ends in "allenisd.org"

<img width="510" alt="image" src="https://user-images.githubusercontent.com/35275250/225729857-3b45e50d-5bdd-4c5e-b73f-78c7aa6ceaab.png">

**Comment by Muq2** [comment]
I will modify the regex soon

**Comment by Muq2** [comment]
[fcf1f1c](https://github.com/CSAllenISD/2023-ISP-ModelScheduler/commit/fcf1f1cbab8fe58905a2f1d44d917ce7a894e044)
