### ISSUE TITLE
FAQ needs redesign

### ISSUE THREAD

**Issue by Reynard-G** [CSAllenISD/2023-ISP-ModelScheduler#132]
The FAQ is bland and needs a redesign along with relevant questions.

**Comment by TahmidR2456** [comment]
I have changed the FAQ page to a more suitable design

**Comment by IsaacDaKing** [comment]
I thought the FAQ didn't look bad, it's not like anyone is very likely to use it, (I guess its still a good thing to have). That being said, your redesign is solid, but maybe we could've diverted that attention elsewhere.
