### ISSUE TITLE
Login Style

### ISSUE THREAD

**Issue by IsaacDaKing** [CSAllenISD/2023-ISP-ModelScheduler#143]
Should we make the login/sign in/ forgot my password page's style match that of the actual app? I guess it's pretty similar to the dark mode though, opinions?

**Comment by TahmidR2456** [comment]
I think the way it looks right now is fine, but maybe doing so would create some consistency

**Comment by lumen-novum** [comment]
I'll look into adding a light/dark mode to the pages that don't currently have it
