### ISSUE TITLE
Database implementation

### ISSUE THREAD

**Issue by Muq2** [CSAllenISD/2023-ISP-ModelScheduler#15]
Once the final database design from the previous issue is decided we need to discuss how we will implement the database into CoderMerlin. I was thinking of exporting the scheme to a script and running a sql command on it in CoderMerlin.

**Comment by Muq2** [comment]
Update: BY will explain mysql and codermerlin in the coming days. Please make sure that the main structure of the database is designed by then.

**Comment by lumen-novum** [comment]
Have you guys created a rough outline of what the database will look like yet?
