### ISSUE TITLE
improve FAQ page designs

### ISSUE THREAD

**Issue by KodingKevin** [CSAllenISD/2023-ISP-ModelScheduler#151]
The FAQ page is way too bland and boring so it'll be improved by making some changes to the styles as well as adding more graphics and images

**Comment by TahmidR2456** [comment]
I think extra images would mess up the flow of style. Not many people visit the FAQ page anyways, so keeping it the way it is right now would be most beneficial.

**Comment by KodingKevin** [comment]
Adding some images shouldn't mess up anything and the images are mostly to fit the other pages since we will be adding them for those as well. Also considering how empty the entire page is adding some graphics is still better than nothing.

**Comment by TahmidR2456** [comment]
What kinds of graphics do we plan to add?

**Comment by KodingKevin** [comment]
Uhhh you'll see 😁

**Comment by IsaacDaKing** [comment]
Is this finished now? FAQ doesn't feel very boring anymore lol

**Comment by KodingKevin** [comment]
Ya Ig
