### ISSUE TITLE
On the Scheduler page add colors to time to correlate to location.

### ISSUE THREAD

**Issue by GetJumpedOn95** [CSAllenISD/2023-ISP-ModelScheduler#159]
Enhancement - Add colors to the side tabs for the start and end times of each period.  AHS should be red and STEAM center should be blue.

Also, fix the times to match the published bell schedule from Allen ISD.
https://www.allenisd.org/Page/25387

These were changed and they do not match these times..

**Comment by GetJumpedOn95** [comment]
Updated the times on scheduler.html, scheduler.js and final.html.  Also added colorized text to the times to help differentiate between the steam times and the AHS times.

**Comment by June3333** [comment]
Those times were correct, commit reverted
https://github.com/CSAllenISD/2023-ISP-ModelScheduler/commit/ff776eb734c5f8aa49a416dbf5b3d490b7fa4c12#comments

**Comment by GetJumpedOn95** [comment]
I had other changes besides that one.
