### ISSUE TITLE
API Endpoints

### ISSUE THREAD

**Issue by ryanhallock** [CSAllenISD/2023-ISP-ModelScheduler#16]
We will use a REST API system to provide class schedules and period availability. 

- [x] We must determine the endpoints required for the project to meet an MVP.
- [x] Implement API endpoints to meet the MVP requirement.

A few of them come to mind to achieve MVP.

- [x]  GET request to get all classrooms
- [x]  POST request to grab all data on selected classes

**Comment by lumen-novum** [comment]
> - [ ] POST request to grab all data on selected classes
What kind of data would we provide on the classes?

**Comment by Muq2** [comment]
When the user logs in we will send the userSchedule table for that use. That table will contain periodID values that correspond to the courses primary key. The courses table will be dumped to json and frontend will lookup course data using periodID sent from the server.
