### ISSUE TITLE
Project Setup

### ISSUE THREAD

**Issue by ryanhallock** [CSAllenISD/2023-ISP-ModelScheduler#17]
- [x] Setup Folders
- [x] Setup Vapor 
- [x] Setup Static Site
- [x] Setup & Define SQL #15 #2 
- [x] Define API endpoints #16 
- [x] Define Frontend Design

**Comment by lumen-novum** [comment]
> - [ ] Setup Static Site

Is there a url to the website yet? Or is the website not published yet?

**Comment by Muq2** [comment]
https://codermerlin.com/vapor/firstname-lastname/
