### ISSUE TITLE
Appoint Product and Project managers along with Release Engineers

### ISSUE THREAD

**Issue by Logan-Rohlfs** [CSAllenISD/2023-ISP-ModelScheduler#22]
No one has been picked as either of these three roles yet and they will need to be appointed by a group vote/decision. If you currently have that as your role please change it. If you arent already in the discord where we have been discussing these things then join here [Model Scheduler Discord](https://discord.gg/aV8RCvt7Cv)

**Comment by IsaacDaKing** [comment]
Unfortunately, I cannot be present on the discord due to the unfortunate condition of being grounded. All my voting powers are vested in Reynard (Or you can remove it in absentia, I don't really care, I'll trust whoever you guys elect).

**Comment by ryanhallock** [comment]
We had a vote inside our discord and it seems @nalyd1369 won project manager. I am going to close this issues as there seems to be no contenders for the other roles.
