### ISSUE TITLE
Push README.md to main after documentation completion

### ISSUE THREAD

**Issue by sap786** [CSAllenISD/2023-ISP-ModelScheduler#23]

**Comment by Reynard-G** [comment]
Do we have a list of all members in this project?

**Comment by IFEELLIKEIMGOKU** [comment]
https://docs.google.com/spreadsheets/d/1FkO3ScF-8j51DM8966VqbcL8iOl_KYXpkZRe2dFMhDA/edit#gid=0

Also 3 students haven't put their name in yet, Aaron Berdecia, Cayson Mayo, and Devin Wingfield.

**Comment by Reynard-G** [comment]
Only Devin Wingfield left
