### ISSUE TITLE
June Documentation

### ISSUE THREAD

**Issue by June3333** [CSAllenISD/2023-ISP-ModelScheduler#25]
Add my github username to the README.md in my repository

Adjacent to my username provide a list of role(s) for which I am responsible

Below my username (indented) add a link to my CoderMerlin Digital Portfolio

**Comment by June3333** [comment]
done

**Comment by June3333** [comment]
![Image](https://user-images.githubusercontent.com/89550025/235279957-8f553bcd-ebbd-4b5a-be3c-92eb96004aeb.png)

**Comment by June3333** [comment]
![Image](https://user-images.githubusercontent.com/89550025/236558789-4a8f1c0f-7fc6-481f-b6e3-fe3d2847f273.png)

**Comment by June3333** [comment]
![Image](https://user-images.githubusercontent.com/89550025/236561716-410118f8-79c1-4c39-8b26-e04048326938.png)

**Comment by June3333** [comment]
![Image](https://github.com/CSAllenISD/2023-ISP-ModelScheduler/assets/89550025/2c3cbaf7-9109-4e2c-9c66-c09dbcea0fc4)

**Comment by June3333** [comment]
![Image](https://github.com/CSAllenISD/2023-ISP-ModelScheduler/assets/89550025/4cd5660f-3b6b-4523-b55b-6ff8dff47ccb)

**Comment by June3333** [comment]
![Image](https://github.com/CSAllenISD/2023-ISP-ModelScheduler/assets/89550025/b7c2098a-abf1-46e6-8855-084efa88093c)

**Comment by IsaacDaKing** [comment]
wtf, are you using your closed  documentation issue for image hosting? lol

**Comment by June3333** [comment]
shh
