### ISSUE TITLE
Link Style Sheet to HTML file

### ISSUE THREAD

**Issue by sap786** [CSAllenISD/2023-ISP-ModelScheduler#33]

**Comment by Muq2** [comment]
Don't push useless issues with no description. Come back when you know how github works.

**Comment by sap786** [comment]
whoa whoa whoa muq2! let’s cool our beans here! didn’t mean to make you that mad buddy. care to explain how github works tho? it’d make me really happy goofballOn Jan 11, 2023, at 1:53 PM, Muq2 ***@***.***> wrote:﻿
Don't push useless issues with no description. Come back when you know how github works.
