### ISSUE TITLE
Creating Github Workflows

### ISSUE THREAD

**Issue by lumen-novum** [CSAllenISD/2023-ISP-ModelScheduler#57]
At the moment, there isn't a way to verify that any backend code pushed to a branch is able to compile and meets the styling requirements for Swift. We could manually verify everytime someone pushes to a branch, but given our limited amount of time, we won't be able to review every single commit.

One way we could possibly solve this issue would be using Github Workflows.

Here is some information about Workflows: (copied from the Github link down below)
> A workflow is a configurable automated process that will run one or more jobs. Workflows are defined by a YAML file checked in to your repository and will run when triggered by an event in your repository, or they can be triggered manually, or at a defined schedule.

> Workflows are defined in the .github/workflows directory in a repository, and a repository can have multiple workflows, each of which can perform a different set of tasks. For example, you can have one workflow to build and test pull requests, another workflow to deploy your application every time a release is created, and still another workflow that adds a label every time someone opens a new issue.

This system would allow the code to be automatically verified everytime someone makes a commit.

We can also use these workflows for other things too, it doesn't have to be just for checking code.

If you want to learn more about Github Workflows, check out [this link.](https://docs.github.com/en/actions/using-workflows/about-workflows)

What do you guys think?

**Comment by devw45** [comment]
I like this idea of an automated workflow that checks code has been pushed, I'm open to learning the code but also understand if another person chooses to do create the file
