### ISSUE TITLE
Front-End Discussion IMPORTANT

### ISSUE THREAD

**Issue by IsaacDaKing** [CSAllenISD/2023-ISP-ModelScheduler#85]
Alright, so we've vaguely figured out some of the roles for the Front-end based on the MVP.

Login Page:   Sahil, TBD
Home Page: Dylan (Project Manager, so he won't be very involved), Layne, Isaac
Schedule Page:   Raeed, Reynard, +1 more?
Final/print Page & FAQ/Devs page: : Avanish, Kevin

Avanish and Kevin are both on Final and FAQ for now because they should be more simple than the rest. Everyone on Front End should be assigned soon. KEEP THE THE MINIMUM VIABLE PRODUCT IN MIND!!! Please reply with role requests or questions.

**Comment by LayneY** [comment]
I can help with other pages as well if needed.

**Comment by KodingKevin** [comment]
I can help with schedule page and the final if needed

**Comment by IsaacDaKing** [comment]
I'll put Kevin down with Avanish on Final. Layne, for now since we just need to get started and we don't have enough roles for everyone in front-end, we'll keep it with just Homepage, when other front end engineers start calling roles, we can reassign more.

**Comment by TahmidR2456** [comment]
Great idea 👍

**Comment by nalyd1369** [comment]
We need to ensure that we talk to the other class periods and see what pages they'd like to work on. I'll make sure to reach out to them over the weekend and see what they want to do.

**Comment by IsaacDaKing** [comment]
Right

**Comment by IsaacDaKing** [comment]
Imma close this since we have new assigned roles and all that jazz
