### ISSUE TITLE
We should rename index to something more descriptive

### ISSUE THREAD

**Issue by nalyd1369** [CSAllenISD/2023-ISP-ModelScheduler#86]

**Comment by IFEELLIKEIMGOKU** [comment]
Maybe something like homePage.html or scheduler.html

**Comment by KodingKevin** [comment]
ya something like home.html is probably good since I named the faq page FAQ.html

**Comment by TahmidR2456** [comment]
Yea I think this is good idea for future additions

**Comment by KrabbiePatty** [comment]
It should probably be named something like login.html because the homepage will probably be named home.html
