### ISSUE TITLE
Create FAQ page

### ISSUE THREAD

**Issue by KodingKevin** [CSAllenISD/2023-ISP-ModelScheduler#87]
Creating a FAQ page that can be linked from the home page

**Comment by nalyd1369** [comment]
Definitely good we're getting this done in this MVP, it's one of the most important pages we'll need

**Comment by AJ789456** [comment]
I think we decided that everyone would create their own style using CSS for their page and then the best design will be used site wide. Sos this page will need a need a CSS file.

**Comment by Muq2** [comment]
Fix the navbar, the sizing is off compared to the other designs.

**Comment by ryanhallock** [comment]
We need a unified navbar, either using leaf templating or another system. Duplicate code is a problem, especially when it needs cross updated when new pages are added, or the design is changed.

**Comment by Muq2** [comment]
Using leaf as a navbar bar template is a good idea.

**Comment by IsaacDaKing** [comment]
I think we have more or less completed the issue here. If we have more specific stuff we want to add to the page, we can create a more specific issue regarding it.
