### ISSUE TITLE
Begin working on the CSS file connected to the FAQ Page

### ISSUE THREAD

**Issue by AJ789456** [CSAllenISD/2023-ISP-ModelScheduler#94]
Begin creating a style for the FAQ page through the use of a CSS file. This style may be used for the rest of the pages in the model scheduler if it turns out good.

**Comment by KrabbiePatty** [comment]
It should be the same CSS page for the entire website because we want the themes to be continuous. Also, I was thinking that we should do a dark theme for the default.

**Comment by June3333** [comment]
The font of the text should change to something contrasting with black when the user has dark mode on for better readability

**Comment by IsaacDaKing** [comment]
I think we are far past this specific issue at this point. Particularly given that we are now planning on merging the CSS files. @June3333 's additional issue is now cataloged in #119 too.
