### ISSUE TITLE
Setting up deadlines in todo list

### ISSUE THREAD

**Issue by lumen-novum** [CSAllenISD/2023-ISP-ModelScheduler#95]
We already have a todo list, an in progress list, and a finished list, but I feel like these lists could be improved if each feature had a specific deadline that we had to achieve.

This might help avoid procrastination and stay on top of our work.

Maybe something like a GNATT chart synced with the different lists would help?

What do you guys think?

**Comment by ryanhallock** [comment]
We can create milestones inside of Github to hold required issues or pull requests to be closed.

**Comment by IsaacDaKing** [comment]
I feel like we, or at least me personally, have a pretty good idea of what we need to do, and seeing as we're now reaching the final week of development, I think this issue has become sort of irrelevant, I suggest closing unless anybody has any objections

**Comment by GetJumpedOn95** [comment]
Yeah I feel like we have a clear sight on what we need to do next.
