### ISSUE TITLE
Website Topology

### ISSUE THREAD

**Issue by KrabbiePatty** [CSAllenISD/2023-ISP-ModelScheduler#96]
Here is a minimal draft for the topology of the website. I plan to add some more stuff. You can put some suggestions in the comments.

![Image](https://user-images.githubusercontent.com/89479023/212769028-e21de4c0-235f-4715-9efd-7c6ef2cd31e8.PNG)

**Comment by GetJumpedOn95** [comment]
This design looks good.  Nice design.
