### ISSUE TITLE
Create CSS Page

### ISSUE THREAD

**Issue by KrabbiePatty** [CSAllenISD/2023-ISP-ModelScheduler#97]
I was thinking that the main style should have a dark theme with red and blue accent colors. There should also be an option for a light theme. I think that this theme should be persistent throughout the entire website.

**Comment by IsaacDaKing** [comment]
Makes sense, MVP should maybe just be light mode and we can add dark mode later. Remember that this is going to be used by a bunch of Brand-Loyalty simpletons incapable of complex thought. As such, idk if default as dark mode will be the most advantageous (speaking as someone who prefers dark mode) , they probably want something bright on their eyes. Those who prefer dark mode are likely to have a modicum of intelligence and be able to change the setting from a switch. Keep in mind that almost all websites have their default set as light mode, and many of these websites are owned by big corporations that utilize their resources to ensure the most optimal UI design possible. (then again none of this really matters too much anyway)

**Comment by GetJumpedOn95** [comment]
The .css pages were very well done. I found them easy to use and update.
